// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmndprsp82TAZkPJ6ck5SqEixBKNiBL5o',
    appId: '1:524165811884:web:857fcbd28cf4d223619909',
    messagingSenderId: '524165811884',
    projectId: 'example-72389',
    authDomain: 'example-72389.firebaseapp.com',
    storageBucket: 'example-72389.firebasestorage.app',
    measurementId: 'G-JGSJRTG28P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQLjSNOx2_pIIFJgvnjEZKdPwXdcKJ8c',
    appId: '1:524165811884:android:a37545e82fdd28ce619909',
    messagingSenderId: '524165811884',
    projectId: 'example-72389',
    storageBucket: 'example-72389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52T7IA6VylOf2Y72VIDaR_5XuOdlvtKY',
    appId: '1:524165811884:ios:56ae3e9491b7c97a619909',
    messagingSenderId: '524165811884',
    projectId: 'example-72389',
    storageBucket: 'example-72389.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52T7IA6VylOf2Y72VIDaR_5XuOdlvtKY',
    appId: '1:524165811884:ios:56ae3e9491b7c97a619909',
    messagingSenderId: '524165811884',
    projectId: 'example-72389',
    storageBucket: 'example-72389.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmndprsp82TAZkPJ6ck5SqEixBKNiBL5o',
    appId: '1:524165811884:web:fd79315fb670b3aa619909',
    messagingSenderId: '524165811884',
    projectId: 'example-72389',
    authDomain: 'example-72389.firebaseapp.com',
    storageBucket: 'example-72389.firebasestorage.app',
    measurementId: 'G-W8X7D7NZXZ',
  );
}
